### PR TITLE
Added threading, removed doCallbacksGenericPointer, added video recording

### PR DESCRIPTION
**Pull request by jwlodek**
## R1-2 (???-July-2019)

* Computer Vision functions implemented
    * Video Record - allows for video recording with areaDetector

* Additional Feature changes
    * Added filepath PV
    * Added filepath exists PV
    * Added opencv_video and opencv_videoio as library dependancies
    * Added support for multithreading for certain functions
    * New medm, edm, and adl screens (Courtesy of Mark Rivers)
    * New rst documentation pages (Courtesy of Mark Rivers)

* Bug Fixes
    * Edited mat2NDArray function to remove potential memory leak
    * Comment + documentation updates
    * Fixed bug where input pArray data would be placed into the Mat - which would result in data overwrite.
    * Removed call that added unnecessary DataType attribute
    * Changed `doCallbacksGenericPointer` to`endProcessCallbacks`
    * Cleanup of `mat2NDArray` function

### CODE REVIEW

**Comment by jwlodek** [comment]
I added a commit to this pull request that uses NDFile.template instead of the records defined in NDCV.template beaffa9817cc6ca73814b6bb1ed7878f024dd0da

**Comment by jwlodek** [comment]
I've added a commit that adds a check in the Makefile for the `WITH_OPENCV_VIDEO` flag. When this is set to `YES`, `ADCompVision` will avoid compiling any code that depends on these libraries, which should make building on older linux distributions easier.

**Comment by MarkRivers** [comment]
>When this is set to YES, ADCompVision will avoid compiling any code that depends on these libraries, which should make building on older linux distributions easier.c

Do you mean set to NO?

**Comment by jwlodek** [comment]
Yes that's right I'm sorry

**Comment by jwlodek** [comment]
Are we OK to merge this? It contains fixes for threading and adds `endProcessCallbacks`.

**Pull request merged**
